### ISSUE TITLE
com.github.salomonbrys.kodein.Kodein$OverridingException: Binding bind<FragmentManager>() with ? { ? } must override an existing binding.

### ISSUE THREAD

**Issue by bonnyfone** [SalomonBrys/Kodein#69]
Hi, I'm trying to use the KodeinSupportFragment and I get this error:

```
 FATAL EXCEPTION: main
  Process: com.here.jumper, PID: 4460
  java.lang.RuntimeException: Unable to resume activity {com.here.jumper/com.here.jumper.flow.main.MainActivity}: com.github.salomonbrys.kodein.Kodein$OverridingException: Binding bind<FragmentManager>() with ? { ? } must override an existing binding.
      at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3791)
      at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3832)
      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2994)
      at android.app.ActivityThread.-wrap14(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6682)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
   Caused by: com.github.salomonbrys.kodein.Kodein$OverridingException: Binding bind<FragmentManager>() with ? { ? } must override an existing binding.
      at com.github.salomonbrys.kodein.KodeinContainer$Builder._checkOverrides(KodeinContainer.kt:220)
      at com.github.salomonbrys.kodein.KodeinContainer$Builder.access$_checkOverrides(KodeinContainer.kt:137)
      at com.github.salomonbrys.kodein.KodeinContainer$Builder$BindBinder.with(KodeinContainer.kt:273)
      at com.github.salomonbrys.kodein.Kodein$Builder$TypeBinder.with(Kodein.kt:192)
      at com.github.salomonbrys.kodein.android.SupportFragmentInjector$initializeInjector$fragmentModule$1.invoke(KodeinAndroidComponents.kt:400)
      at com.github.salomonbrys.kodein.android.SupportFragmentInjector$initializeInjector$fragmentModule$1.invoke(KodeinAndroidComponents.kt:383)
      at com.github.salomonbrys.kodein.Kodein$Builder.<init>(Kodein.kt:176)
      at com.github.salomonbrys.kodein.Kodein$Builder.import(Kodein.kt:273)
      at com.github.salomonbrys.kodein.android.KodeinAndroidComponentsKt$_inject$kodein$1.invoke(KodeinAndroidComponents.kt:37)
      at com.github.salomonbrys.kodein.android.KodeinAndroidComponentsKt$_inject$kodein$1.invoke(KodeinAndroidComponents.kt)
      at com.github.salomonbrys.kodein.Kodein$Builder.<init>(Kodein.kt:176)
      at com.github.salomonbrys.kodein.internal.KodeinImpl.<init>(KodeinImpl.kt:48)
      at com.github.salomonbrys.kodein.Kodein$Companion.invoke(Kodein.kt:423)
      at com.github.salomonbrys.kodein.Kodein$Companion.invoke$default(Kodein.kt:423)
      at com.github.salomonbrys.kodein.android.KodeinAndroidComponentsKt._inject(KodeinAndroidComponents.kt:34)
      at com.github.salomonbrys.kodein.android.KodeinAndroidComponentsKt.access$_inject(KodeinAndroidComponents.kt:1)
      at com.github.salomonbrys.kodein.android.SupportFragmentInjector$DefaultImpls.initializeInjector(KodeinAndroidComponents.kt:408)
      at com.github.salomonbrys.kodein.android.KodeinSupportFragment.initializeInjector(KodeinAndroidComponents.kt:421)
      at com.github.salomonbrys.kodein.android.KodeinSupportFragment.onCreate(KodeinAndroidComponents.kt:425)
      at ******.onCreate(BaseFlowFragment.kt:20)
```

This is the BaseFlowFragment (extended by other fragments):

```
abstract class BaseFlowFragment<T : ViewModel>() : KodeinSupportFragment(), LifecycleRegistryOwner {

    internal var mLifecycleRegistry = LifecycleRegistry(this)

    override fun getLifecycle(): LifecycleRegistry {
        return mLifecycleRegistry
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //..
    }
    //..
}
```

Any idea?

**Comment by joecks** [comment]
The `KodeinSupportFragment` works in conjunction with the `FragmentActivityInjector` as a host Activity.

**Comment by bonnyfone** [comment]
Thanks, I was using ActivityInjector instead.

**Comment by fablue** [comment]
First of all: I love your work with Kodein 👍

I had the same issue because I did not see this in the docs either. I think it would make sense to mention it. Sorry if it is already mentioned =)
