### ISSUE TITLE
CompositeTypeToken problem

### ISSUE THREAD

**Issue by salongbass** [SalomonBrys/Kodein#74]
```
class KodeinTest {

    open class A<S>

    open class B<X> : A<X>()

    class C : B<String>()

    @Test
    fun test() {
        val t = CompositeTypeToken<B<String>>(erased(), TT(String::class.java))
        println(t.simpleDispString())
        val kodein = Kodein {
            bind<B<String>>() with provider { C() }
        }
        kodein.Instance<B<String>>(t)
    }
}
```

But I failed to retrieve an instance by composite type token

```
com.github.salomonbrys.kodein.Kodein$NotFoundException: No provider found for bind<KodeinTest.B<String>>() with ? { ? }
Registered in Kodein:
        bind<KodeinTest.B<String>>() with provider { KodeinTest.C } 
	at com.github.salomonbrys.kodein.KodeinContainer$DefaultImpls._notFoundException(KodeinContainer.kt:32)
	at com.github.salomonbrys.kodein.KodeinContainer$DefaultImpls.nonNullProvider(KodeinContainer.kt:75)
	at com.github.salomonbrys.kodein.internal.KodeinContainerImpl.nonNullProvider(KodeinContainerImpl.kt:17)
	at com.github.salomonbrys.kodein.Kodein$DefaultImpls.Instance(Kodein.kt:396)
	at com.github.salomonbrys.kodein.internal.KodeinImpl.Instance(KodeinImpl.kt:13)
	at com.github.salomonbrys.kodein.Kodein$DefaultImpls.Instance$default(Kodein.kt:396)
	at cn.org.cicada.mobile.ui.KodeinTest.test(KodeinTest.kt:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by SalomonBrys** [comment]
You must understand that composite type tokens are used only manually.
When you use bind<B<String>>() with provider { C() }, it will bind to:

- An automatically defined `ParameterizedType` if you are using regular (generic-able) Kodein.
- `T::class.java` if you are using Kodein-erased.

If you want to bind with a `CompositeTypeToken`, you must do it manually:

```
val kodein = Kodein {
    Bind(t) with provider { C() }
}
```

TypeTokens cannot be automatic, they exist to allow generic binding in an erased environment, and therefore cannot, by essence, be created by the compiler.

By the way, you should declare the token like this (easier syntax):

```
val t = erasedComp1<B<String>, String>()
```
